[build]
publish = "public"
command = "npm run build"
functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

  from = "/assets/css/nan-landing-pages.css"
  to = "/assets/css/nan-landing-pages.webflow.css"
  status = 301
  force = true